// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package network

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadActivity returns the embedded CollectionSpec for activity.
func loadActivity() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ActivityBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load activity: %w", err)
	}

	return spec, err
}

// loadActivityObjects loads activity and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*activityObjects
//	*activityPrograms
//	*activityMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadActivityObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadActivity()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// activitySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type activitySpecs struct {
	activityProgramSpecs
	activityMapSpecs
	activityVariableSpecs
}

// activityProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type activityProgramSpecs struct {
	RecordActivity *ebpf.ProgramSpec `ebpf:"record_activity"`
}

// activityMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type activityMapSpecs struct {
	ActivityByUserId  *ebpf.MapSpec `ebpf:"activity_by_user_id"`
	WakeStateByUserId *ebpf.MapSpec `ebpf:"wake_state_by_user_id"`
}

// activityVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type activityVariableSpecs struct {
	VirtualMachineUserId *ebpf.VariableSpec `ebpf:"virtual_machine_user_id"`
}

// activityObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadActivityObjects or ebpf.CollectionSpec.LoadAndAssign.
type activityObjects struct {
	activityPrograms
	activityMaps
	activityVariables
}

func (o *activityObjects) Close() error {
	return _ActivityClose(
		&o.activityPrograms,
		&o.activityMaps,
	)
}

// activityMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadActivityObjects or ebpf.CollectionSpec.LoadAndAssign.
type activityMaps struct {
	ActivityByUserId  *ebpf.Map `ebpf:"activity_by_user_id"`
	WakeStateByUserId *ebpf.Map `ebpf:"wake_state_by_user_id"`
}

func (m *activityMaps) Close() error {
	return _ActivityClose(
		m.ActivityByUserId,
		m.WakeStateByUserId,
	)
}

// activityVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadActivityObjects or ebpf.CollectionSpec.LoadAndAssign.
type activityVariables struct {
	VirtualMachineUserId *ebpf.Variable `ebpf:"virtual_machine_user_id"`
}

// activityPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadActivityObjects or ebpf.CollectionSpec.LoadAndAssign.
type activityPrograms struct {
	RecordActivity *ebpf.Program `ebpf:"record_activity"`
}

func (p *activityPrograms) Close() error {
	return _ActivityClose(
		p.RecordActivity,
	)
}

func _ActivityClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed activity_x86_bpfel.o
var _ActivityBytes []byte
